# Generated by Django 3.1.7 on 2021-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_stars',
        ),
    ]
